// action types

export enum ActionConstants {
    // ADD_TASK_LOAD = 'ADD_TASK_LOAD',
    ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS',

    // DELETE_TASK_LOAD = 'DELETE_TASK_LOAD',
    DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS',

    // EDIT_TASK_LOAD = 'EDIT_TASK_LOAD',
    EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS',

    RESET_NAVIGATION = 'RESET_NAVIGATION',

    SET_ERROR = 'SET_ERROR',

    SYNC_TASKS_REQUEST = 'SYNC_TASKS_REQUEST',
    SYNC_TASKS_SUCCESS = 'SYNC_TASKS_SUCCESS',
    SYNC_TASKS_FAILURE = 'SYNC_TASKS_FAILURE',
}